# Generated by Django 4.1.7 on 2023-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(default=0, unique=True),
        ),
    ]
