# Generated by Django 4.1.7 on 2023-04-09 09:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagina_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
