# Generated by Django 4.1.7 on 2023-04-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pagina_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='titulo',
        ),
    ]
