# Generated by Django 4.1.7 on 2023-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pagina_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
