# Generated by Django 4.1.7 on 2023-04-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='imagen',
            field=models.ImageField(upload_to='paginas'),
        ),
    ]
