# Generated by Django 4.1.7 on 2023-04-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
