# Generated by Django 4.1.7 on 2023-04-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='perfil',
        ),
    ]
