# Generated by Django 4.1.7 on 2023-04-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_autor_blog_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='num_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
