# Generated by Django 4.1.7 on 2023-04-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_categoria_blog_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=0, unique=True),
        ),
    ]
