# Generated by Django 4.1.7 on 2023-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categorias',
        ),
        migrations.AddField(
            model_name='categoria',
            name='noticias',
            field=models.ManyToManyField(related_name='categorias', to='blog.blog'),
        ),
    ]
