# Generated by Django 4.1.7 on 2023-04-09 09:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_categorias_categoria_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
