# Generated by Django 4.1.7 on 2023-04-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secreto',
            old_name='texto',
            new_name='mensaje',
        ),
    ]
