# Generated by Django 4.1.7 on 2023-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretos', '0002_rename_texto_secreto_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secreto',
            name='hash',
            field=models.CharField(max_length=250),
        ),
    ]
